### ISSUE TITLE
Add your fake details

### ISSUE THREAD

**Issue by Banshaj-Paudel** [Banshaj-Paudel/Git_GitHub_Workshop#2]
## Create a <yourname>.md file and add your fake details in there

**Comment by prasiddha98** [comment]
assign me this

**Comment by Banshaj-Paudel** [comment]
Okay

**Comment by prasiddha98** [comment]
i have create a new user please check and merge.  #5

**Comment by Banshaj-Paudel** [comment]
Great! Issue Resolved!

**Comment by Banshaj-Paudel** [comment]
Hey @prasiddha98  I don't see your file. Could you try pushing again

**Comment by prasiddha98** [comment]
#6 here it is
