### ISSUE TITLE
Add your information

### ISSUE THREAD

**Issue by Banshaj-Paudel** [Banshaj-Paudel/Git_GitHub_Workshop#8]
Please create a README file with your name and push it into this repo. Make sure to include the following information, rest you can add more:

1. Name
2. Course Title
3. College Name
4. GitHub Account

**Comment by Firojpaudel** [comment]
hum contribute karenge....

**Comment by Banshaj-Paudel** [comment]
Okay go ahead!

**Comment by Banshaj-Paudel** [comment]
Great! PR Merged. Let's close this issue!
